# Generated by Django 5.0.4 on 2024-05-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_orderitem_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
